
# mysql
spring:
  datasource:
    #MySQL配置
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studySupervision?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  aop:
    auto: true
    proxy-target-class: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.demo.model
server:
  port: 9000
